Resolve multiple definition linker error in CI pipeline
Very confused why I didn't run into this locally. I've confirmed that it
doesn't fail if I run exactly the command from the pipline

    cargo build --release --all-targets --all-features

I'm pretty stumped ...

    error: linking with `cc` failed: exit status: 1
    |
    = note: LC_ALL="C" PATH="..." VSLANG="1033" "cc" "-m64" "/tmp/rustcyU2Dkp/symbols.o" "streamline-b034084ca9f1d1be.streamline.f13b1b7a453383e6-cgu.0.rcgu.o" "streamline-b034084ca9f1d1be.131hj5krsq9cme8k.rcgu.o" "-Wl,--as-needed" "-L" "/home/runner/work/generative/generative/target/release/deps" "-L" "/home/runner/work/generative/generative/target/release/build/generative-1660779e9f48ebab/out/../../../lib/" "-L" "/home/runner/work/generative/generative/target/release/build/generative-1660779
    = note: /usr/bin/ld: libgenerative-371a208ecd8b53b1.rlib(64ef1808e8373b88-noder_ffi.rs.o): in function `from_nodes_edges(rust::cxxbridge1::Slice<CoordShim const>, rust::cxxbridge1::Slice<GraphEdge const>)':
            noder_ffi.rs.cc:(.text._Z16from_nodes_edgesN4rust10cxxbridge15SliceIK9CoordShimEENS1_IK9GraphEdgeEE+0x0): multiple definition of `from_nodes_edges(rust::cxxbridge1::Slice<CoordShim const>, rust::cxxbridge1::Slice<GraphEdge const>)'; libgenerative-371a208ecd8b53b1.rlib(64ef1808e8373b88-geometry_graph_ffi.rs.o):geometry_graph_ffi.rs.cc:(.text._Z16from_nodes_edgesN4rust10cxxbridge15SliceIK9CoordShimEENS1_IK9GraphEdgeEE+0x0): first defined here
            collect2: error: ld returned 1 exit status

    error: linking with `cc` failed: exit status: 1
    |
    = note: LC_ALL="C" PATH="..." VSLANG="1033" "cc" "-m64" "/tmp/rustcHU4n2V/symbols.o" "generative-11c13dcb56c20c9a.generative.882b621103f6f16d-cgu.00.rcgu.o" "generative-11c13dcb56c20c9a.generative.882b621103f6f16d-cgu.01.rcgu.o" "generative-11c13dcb56c20c9a.generative.882b621103f6f16d-cgu.02.rcgu.o" "generative-11c13dcb56c20c9a.generative.882b621103f6f16d-cgu.03.rcgu.o" "
    = note: /usr/bin/ld: libcxxbridge.a(64ef1808e8373b88-noder_ffi.rs.o): in function `from_nodes_edges(rust::cxxbridge1::Slice<CoordShim const>, rust::cxxbridge1::Slice<GraphEdge const>)':
            noder_ffi.rs.cc:(.text._Z16from_nodes_edgesN4rust10cxxbridge15SliceIK9CoordShimEENS1_IK9GraphEdgeEE+0x0): multiple definition of `from_nodes_edges(rust::cxxbridge1::Slice<CoordShim const>, rust::cxxbridge1::Slice<GraphEdge const>)'; libcxxbridge.a(64ef1808e8373b88-geometry_graph_ffi.rs.o):geometry_graph_ffi.rs.cc:(.text._Z16from_nodes_edgesN4rust10cxxbridge15SliceIK9CoordShimEENS1_IK9GraphEdgeEE+0x0): first defined here
            collect2: error: ld returned 1 exit status

Update: While it was a problem that the function wasn't inlined - the
real cause seems to have been the CI pipeline cache.